### ISSUE TITLE
vivoY75和ZTE BA520扫描崩溃（不是必发，但是发生的频率挺高）

### ISSUE THREAD

**Issue by jinke1984** [pqpo/SmartCamera#10]
错误日志：
java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:877)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:856)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:823)
        at me.pqpo.smartcameralib.SmartScanner.preparePreviewBitmap(SmartScanner.java:126)
        at me.pqpo.smartcameralib.SmartScanner.previewScan(SmartScanner.java:114)
        at me.pqpo.smartcameralib.SmartCameraView$ScanThread.run(SmartCameraView.java:205)

**Comment by pqpo** [comment]
新版本试试，已经修复了
