### ISSUE TITLE
Android 4.1.2 运行崩溃

### ISSUE THREAD

**Issue by hVenus** [pqpo/SmartCamera#30]
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity ComponentInfo{me.pqpo.scan/me.pqpo.scan.MainActivity}: android.view.InflateException: Binary XML file line #10: Error inflating class me.pqpo.smartcameralib.SmartCameraView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2127)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2152)
        at android.app.ActivityThread.access$700(ActivityThread.java:144)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1258)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4944)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1043)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.view.InflateException: Binary XML file line #10: Error inflating class me.pqpo.smartcameralib.SmartCameraView
        at android.view.LayoutInflater.createView(LayoutInflater.java:619)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at me.pqpo.scan.MainActivity.onCreate(MainActivity.java:61)
        at android.app.Activity.performCreate(Activity.java:5185)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2091)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2152) 
        at android.app.ActivityThread.access$700(ActivityThread.java:144) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1258) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:4944) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1043) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
        at android.view.LayoutInflater.createView(LayoutInflater.java:593)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:752) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
        at me.pqpo.scan.MainActivity.onCreate(MainActivity.java:61) 
        at android.app.Activity.performCreate(Activity.java:5185) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2091) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2152) 
        at android.app.ActivityThread.access$700(ActivityThread.java:144) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1258) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:4944) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1043) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.ExceptionInInitializerError
        at me.pqpo.smartcameralib.SmartCameraView.init(SmartCameraView.java:50)
        at me.pqpo.smartcameralib.SmartCameraView.<init>(SmartCameraView.java:45)
        at me.pqpo.smartcameralib.SmartCameraView.<init>(SmartCameraView.java:40)
        at java.lang.reflect.Constructor.constructNative(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:593) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:752) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
        at me.pqpo.scan.MainActivity.onCreate(MainActivity.java:61) 
        at android.app.Activity.performCreate(Activity.java:5185) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2091) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2152) 
        at android.app.ActivityThread.access$700(ActivityThread.java:144) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1258) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:4944) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1043) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: link_image[1891]:   102 could not load needed library 'libgnustl_shared.so' for 'libsmart_camera.so' (load_library[1093]: Library 'libgnustl_shared.so' not found)
        at java.lang.Runtime.loadLibrary(Runtime.java:370)
        at java.lang.System.loadLibrary(System.java:535)
        at me.pqpo.smartcameralib.SmartScanner.<clinit>(SmartScanner.java:150)
        at me.pqpo.smartcameralib.SmartCameraView.init(SmartCameraView.java:50) 
        at me.pqpo.smartcameralib.SmartCameraView.<init>(SmartCameraView.java:45) 
        at me.pqpo.smartcameralib.SmartCameraView.<init>(SmartCameraView.java:40) 
        at java.lang.reflect.Constructor.constructNative(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:593) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:752) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
        at me.pqpo.scan.MainActivity.onCreate(MainActivity.java:61) 
        at android.app.Activity.performCreate(Activity.java:5185) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2091) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2152) 
        at android.app.ActivityThread.access$700(ActivityThread.java:144) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1258) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:4944) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1043) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810) 
        at dalvik.system.NativeStart.main(Native Method) 

没有导入源码，是新建工程，用添加依赖的方式引用你的库。
在 Android 8.0上正常。
在Android 4.1.2  和  4.2 上启动崩溃。报以上错误。

请指教该如何处理.

**Comment by geekqian** [comment]
@hVenus 
http://www.geekqian.com/post/a6f3e92a.html

**Comment by hVenus** [comment]
@geekqian 用的添加依赖的方法，没法改这个配置啊！！！
非要导入源码吗？

**Comment by geekqian** [comment]
> @geekqian 用的添加依赖的方法，没法改这个配置啊！！！
> 非要导入源码吗？

不是的, 我是先用原始工程编译生成了so包, 之后放到我的工程中使用的, 我也跟你一样是添加依赖的方法.

**Comment by w13897215200** [comment]
求解啊，我导入了so文件还是报错啊

**Comment by geekqian** [comment]
> 求解啊，我导入了so文件还是报错啊

什么样的错误. 贴出来看看

**Comment by w13897215200** [comment]
![image](https://user-images.githubusercontent.com/16714931/59670056-d34fa680-91ed-11e9-8817-4be7ea0f7027.png)

**Comment by w13897215200** [comment]
我是直接把你的so库放到jniLibs里

**Comment by geekqian** [comment]
> 我是直接把你的so库放到jniLibs里

![image](https://user-images.githubusercontent.com/15983385/59670739-fe86c580-91ee-11e9-8a5d-9a822d081da1.png)
![image](https://user-images.githubusercontent.com/15983385/59670955-62a98980-91ef-11e9-8814-2a729d2a146f.png)
然后 clean, rebuild, Invalidate and Restart.

**Comment by w13897215200** [comment]
好的我试一下！
![image](https://user-images.githubusercontent.com/16714931/59671329-0c891600-91f0-11e9-8e53-9a8ccfc46795.png)
这个用删掉吗

**Comment by geekqian** [comment]
![image](https://user-images.githubusercontent.com/15983385/59671229-e6637600-91ef-11e9-8d9d-29d9e934fa53.png)
![image](https://user-images.githubusercontent.com/15983385/59671439-3b06f100-91f0-11e9-95c7-67f9cc6e8da5.png)
@w13897215200

**Comment by w13897215200** [comment]
大神，能给个qq吗，这问题困扰一天了。。万分感谢

**Comment by w13897215200** [comment]
![image](https://user-images.githubusercontent.com/16714931/59672182-971e4500-91f1-11e9-84fe-9d912a1e6650.png)
![image](https://user-images.githubusercontent.com/16714931/59672216-a0a7ad00-91f1-11e9-9680-ccbb1e3eefda.png)

**Comment by w13897215200** [comment]
这样改了之后，我自己项目的一个有道图文识别的库
![image](https://user-images.githubusercontent.com/16714931/59672263-b9b05e00-91f1-11e9-80d0-646b6d1a4030.png)报错了

**Comment by w13897215200** [comment]
![image](https://user-images.githubusercontent.com/16714931/59672324-d64c9600-91f1-11e9-9262-94ad9479bc23.png)

**Comment by w13897215200** [comment]
![image](https://user-images.githubusercontent.com/16714931/59672382-f3816480-91f1-11e9-8d06-c9ccc3761b8b.png)

**Comment by w13897215200** [comment]
![image](https://user-images.githubusercontent.com/16714931/59672415-009e5380-91f2-11e9-8905-508971270e2c.png)

**Comment by w13897215200** [comment]
> ![image](https://user-images.githubusercontent.com/15983385/59671229-e6637600-91ef-11e9-8d9d-29d9e934fa53.png)
> ![image](https://user-images.githubusercontent.com/15983385/59671439-3b06f100-91f0-11e9-95c7-67f9cc6e8da5.png)
> @w13897215200

**Comment by geekqian** [comment]
> 这样改了之后，我自己项目的一个有道图文识别的库
> ![image](https://user-images.githubusercontent.com/16714931/59672263-b9b05e00-91f1-11e9-80d0-646b6d1a4030.png)报错了

把v7a包里的so丢到armeabi, 然后删除v7a, x86两个包

**Comment by w13897215200** [comment]
这样操作了还是报错
![image](https://user-images.githubusercontent.com/16714931/59680114-2bdd6e80-9203-11e9-8931-d52fa07e096a.png)
![image](https://user-images.githubusercontent.com/16714931/59680135-37c93080-9203-11e9-9e5b-bbeb2524e3ed.png)


![image](https://user-images.githubusercontent.com/16714931/59680168-46afe300-9203-11e9-81e2-62c78382ae41.png)

**Comment by geekqian** [comment]
> 这样操作了还是报错
> ![image](https://user-images.githubusercontent.com/16714931/59680114-2bdd6e80-9203-11e9-8931-d52fa07e096a.png)
> ![image](https://user-images.githubusercontent.com/16714931/59680135-37c93080-9203-11e9-9e5b-bbeb2524e3ed.png)
> 
> ![image](https://user-images.githubusercontent.com/16714931/59680168-46afe300-9203-11e9-81e2-62c78382ae41.png)

参考下我这个博客, http://www.geekqian.com/post/a6f3e92a.html 自己编译一个armeabi的so文件导进去吧. 可能v7a的包不适用于armeabi吧. 不行再邮件联系我. 有时间帮你看看

**Comment by pqpo** [comment]
尝试使用最新版本：v2.0.0
https://github.com/pqpo/SmartCamera/releases
