### ISSUE TITLE
部分机型上出现问题, onResume调用了start() startScan

### ISSUE THREAD

**Issue by wzsee** [pqpo/SmartCamera#44]
java.lang.IllegalStateException: Camera is not ready. Call start() before takePicture().
	at com.google.android.cameraview.CameraImpl.takePicture(CameraImpl.java:298)
	at com.google.android.cameraview.CameraView.takePicture(CameraView.java:401)
	at com.zwys.spfscan.page.ScanCameraActivity.onClick(ScanCameraActivity.java:155)
	at com.zwys.spfscan.page.ScanCameraActivity_ViewBinding$2.doClick(ScanCameraActivity_ViewBinding.java:56)
	at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18)
	at android.view.View.performClick(View.java:6659)
	at android.view.View.performClickInternal(View.java:6631)
	at android.view.View.access$3100(View.java:790)
	at android.view.View$PerformClick.run(View.java:26187)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by qq724418408** [comment]
是什么机型
