### ISSUE TITLE
java.lang.IllegalArgumentException: width and height must be > 0

### ISSUE THREAD

**Issue by tao72909** [pqpo/SmartCamera#6]
![image](https://user-images.githubusercontent.com/3013838/45615223-79735200-ba9e-11e8-82b4-1325e8fa96af.png)

09-17 17:22:48.563 4344-4344/? E/MultiWindowProxy: getServiceInstance failed!
09-17 17:22:49.717 4344-4425/me.pqpo.smartcamera E/OpenGLRenderer: PerfServiceNative_notifyRenderTime init fail!
09-17 17:22:50.224 4344-4443/me.pqpo.smartcamera E/AndroidRuntime: FATAL EXCEPTION: processThread
    Process: me.pqpo.smartcamera, PID: 4344
    java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:829)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:775)
        at me.pqpo.smartcameralib.SmartScanner.preparePreviewBitmap(SmartScanner.java:124)
        at me.pqpo.smartcameralib.SmartScanner.previewScan(SmartScanner.java:112)
        at me.pqpo.smartcameralib.SmartCameraView$1.onPicturePreview(SmartCameraView.java:60)
        at com.google.android.cameraview.CameraView$CallbackBridge.onPicturePreview(CameraView.java:470)
        at com.google.android.cameraview.Camera1$2.handleMessage(Camera1.java:110)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by tao72909** [comment]
Good Job
